FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-inference:2.0.1-gpu-py310-cu118-ubuntu20.04-sagemaker

# Set up working directory
WORKDIR /app

# Install dependencies
COPY . .
RUN pip install --upgrade pip && pip install uv && uv pip install --system -e .

# Set environment variables
ENV PYTHONPATH=/app
ENV SAGEMAKER_PROGRAM=src/text2cypher/api/inference.py
