ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# Set up working directory
WORKDIR /app

# Install dependencies
COPY . .
RUN pip install --upgrade pip && pip install uv && uv pip install --system -e .

# Set environment variables
ENV PYTHONPATH=/app
ENV SAGEMAKER_PROGRAM=src/text2cypher/api/inference.py
